name: Ping Proximity XI

on:
  schedule:  
    # Runs every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  ping_job:
    runs-on: ubuntu-latest

    steps:
    - name: Send HTTP request to Proximity XI
      run: |
        curl -I https://proximity-xi.vercel.app/
